title: 厦门送亲之旅
author: Donghuo Zeng
email: donghuozeng@gmail.com
description: >-
  ....

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
